### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by Raynos** [Raynos/browserify-server#1]
The CLI doesn't work in windows

**Comment by Raynos** [comment]
@domenic any idea on windows equivelant of `#!/usr/bin/env node` ?

**Comment by domenic** [comment]
It actually should work, hmm. Check out my opener project for an example. I can look at it in more detail tomorrow.

**Comment by domenic** [comment]
Works great on Windows 8, Node 32-bit. Was able to serve up static files. Optional dependency rbytes (via sockjs via shoe) failed to install but that doesn't seem to have impacted things.

**Comment by Raynos** [comment]
@domenic  sweet

**Comment by Raynos** [comment]
This module is deprecated.
