### ISSUE TITLE
Specify entry file

### ISSUE THREAD

**Issue by ralt** [Raynos/browserify-server#3]
For the life of me, I can't find out how to specify the entry file. I know how to specify the static folder, but I have no idea about the equivalent of the `--entry` option in browserify.

**Comment by Raynos** [comment]
@Ralt the defaults are either use `index.js` or put them in the `cwd/entry` folder.

You don't get anything more then that.

[The code](https://github.com/Raynos/browserify-server/blob/master/index.js#L23) says it will map index -> bundle and entry/x -> entry/x

**Comment by ralt** [comment]
Okay, I can only use index.js then, thanks for the info.
