### ISSUE TITLE
Bundle not rebuilt when launched

### ISSUE THREAD

**Issue by mikolalysenko** [Raynos/browserify-server#5]
Also the server does not watch for changes to files and rebundle.  This is a feature in browserify, so it shouldn't be too difficult to do.

**Comment by Raynos** [comment]
@mikolalysenko that's not what the server should do or how it should be used currently.

See an [example Makefile](https://github.com/Raynos/browserify-server/blob/master/resources/Makefile)

The server is a static HTTP server.

To get new files you run a watcher of choice and have it re-bundle them

**Comment by mikolalysenko** [comment]
I see.  I was thinking that it was supposed to watch and rebundle my code as I was developing it, maybe I had the wrong idea then.

**Comment by Raynos** [comment]
@mikolalysenko it originally did that but that wasn't hackable. A auto scaffolded Makefile is more flexible since I can just tweak and hack the makefile locally instead of tweaking the entire server by passing a massive list of options.

**Comment by mikolalysenko** [comment]
Well, I would just be happy with the original thing then (and I'll probably leave serverify as it is, since that is basically what it does).  For most of my quick projects I don't find that I need or even want to tweak any options, since all I want is some way to get bundle loaded up launched in my browser (and for anything more substantial, I'd probably just write a new server myself anyway).

The main use case that I am thinking of is basically prototyping quick demos in a browser; for example stuff like this:

http://mikolalysenko.github.com/rle-core/life3d/index.html

Autogenerated makefiles seem like overkill for this sort of thing...

**Comment by Raynos** [comment]
I have the same use-case except I've found that a single CLI that does it all was too restricting if I wanted to make the example more complex. Maybe I should go back to that approach with a mind for minimalism.

**Comment by mikolalysenko** [comment]
Well, I think there is enough room in the world for both.  Looking back on my project, the stuff I wrote was a bit too harsh (though part of that was borne out of some frustration with browserify-server).   I could probably stand to tone down the language in my readme.md on serverify

**Comment by Raynos** [comment]
@mikolalysenko I understand the frustration. The original version was too opinionated and did too little. 

The current version came from a desire to scaffold out [this example](https://github.com/Raynos/painter/tree/master/examples/paint)

**Comment by Raynos** [comment]
@mikolalysenko also come hang in #stackvm (on freenode) with @maxogden and @substack

**Comment by mikolalysenko** [comment]
Ok, I'll head on over

**Comment by Raynos** [comment]
This module is deprecated.
