### ISSUE TITLE
Server caches files

### ISSUE THREAD

**Issue by mikolalysenko** [Raynos/browserify-server#6]
By default ecstatic caches files.  This behavior may be desirable in a production environment, but for testing and development it is pretty annoying, since you can't see your changes in real time.

**Comment by Raynos** [comment]
@mikolalysenko ecstatic doesn't cache my index.html or at least I don't have to restart the server when it changes.

What files are you finding ecstatic caches? I've found ecstatic not to cache aggressively by default.

**Comment by Raynos** [comment]
This module is deprecated.
