### ISSUE TITLE
Bundle command is redundant

### ISSUE THREAD

**Issue by mikolalysenko** [Raynos/browserify-server#7]
node-browserify already does this, why should browserify-server replicate this functionality?

**Comment by Raynos** [comment]
https://github.com/Raynos/browserify-server/blob/master/index.js#L22

bundle adds `.html`, `.svg` and `process.env.NODE_ENV` support. Those will be factored out into "browserify 2.0 plugins" at some point.

**Comment by mikolalysenko** [comment]
I see, though maybe this feature could be moved into a separate library?

**Comment by Raynos** [comment]
Your more modular then me. This is MADNESS.

**Comment by mikolalysenko** [comment]
Haha :)

Though I think the real difference in perspective is that I probably have much  more modest demands of what I want a `browserify-server` to do.

**Comment by Raynos** [comment]
This module is deprecated.
